services:
  postgres:
    image: postgres:16-alpine
    container_name: device-api-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=device_db
      - POSTGRES_USER=device_user
      - POSTGRES_PASSWORD=device_verysecurepassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: